name              "symfony"
maintainer        "Jochen Emig"
maintainer_email  "jsemig@gmail.com"
license           "MIT"
description       "Chef extension for Symfony commands"
version           "1.0.0"